title: GitHub Learning
author: jamesiskindanubby
email: anthonycat4@gmail.com
description: > # this means to ignore newlines until "baseurl:"
I recently learned how to use GitHub.
I will show you how to use it.

# social links
twitter_username: j_vmess
github_username:  jamesiskindanubby

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
